dist: bionic
language: minimal

services:
  - docker

env:
  global:
  - NJOBS="2"
  - CONTRIB_NAME=${TRAVIS_REPO_SLUG}
  matrix:
  - COQ_IMAGE="coqorg/coq:dev"
  - COQ_IMAGE="coqorg/coq:8.11"
  - COQ_IMAGE="coqorg/coq:8.10"
  - COQ_IMAGE="coqorg/coq:8.9"

install: |
  # Prepare the COQ container
  docker pull ${COQ_IMAGE}
  docker run -d -i --init --name=COQ -v ${TRAVIS_BUILD_DIR}:/home/coq/${CONTRIB_NAME} -w /home/coq/${CONTRIB_NAME} ${COQ_IMAGE}
  docker exec COQ /bin/bash --login -c "
    export PS4='+ \e[33;1m(\$0 @ line \$LINENO) \$\e[0m '
    set -ex
    if [ -n \"\${COMPILER_EDGE}\" ]; then opam switch \${COMPILER_EDGE}; eval \$(opam env); fi
    " install

script:
- echo -e "${ANSI_YELLOW}Building ${CONTRIB_NAME}...${ANSI_RESET}" && echo -en 'travis_fold:start:script\\r'
- |
  docker exec COQ /bin/bash --login -c "
    export PS4='+ \e[33;1m(\$0 @ line \$LINENO) \$\e[0m '
    set -ex
    sudo chown -R coq:coq /home/coq/${CONTRIB_NAME}
    make -j ${NJOBS}
    " script
- echo -en 'travis_fold:end:script\\r'

after_script:
- docker stop COQ
